name: Ubuntu 20.04 i386 arch fix
description: Allows to install i386 packages
branding:
  icon: message-circle
  color: green

inputs:
  add_i386:
    description: Add i386 arch
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - run: |
        set -xeu -o pipefail
        $GITHUB_ACTION_PATH/gha.sh
      shell: bash
      env:
        INPUT_ADD_I386: ${{ inputs.add_i386 }}
